[package]
name = "webcam-mouse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = { version = "0.7.0", features = ["image"] }
image = "0.24.1"
nokhwa = { version = "0.9.4", features = ["input-v4l", "output-threaded"] }
